import type { ReactNode } from 'react'
import { Handle, Position } from '@xyflow/react'
import { Search, BarChart3, Shield, Sparkles } from 'lucide-react'
import { AGENT_COLORS, AGENT_TOOLTIPS, CHARS_PER_TOKEN, wasTruncated } from '../lib/agents'
import type { AgentRole, AgentState, AgentStatus } from '../types'

const ICONS: Record<AgentRole, ReactNode> = {
  researcher: <Search size={16} />,
  analyst: <BarChart3 size={16} />,
  critic: <Shield size={16} />,
  synthesizer: <Sparkles size={16} />,
}

const STATUS_LABELS: Record<AgentStatus, string> = {
  idle: 'waiting to start',
  thinking: 'thinking',
  working: 'working',
  complete: 'finished',
  stopped: 'stopped before finishing',
  error: 'failed',
}

function statusColor(role: AgentRole, status: AgentStatus): string {
  if (status === 'complete') return '#00ff88'
  if (status === 'error') return '#ff3366'
  if (status === 'stopped') return '#ffa500'
  if (status === 'working' || status === 'thinking') return AGENT_COLORS[role]
  return '#94a3b8'
}

export function AgentNode({ data }: { data: AgentState }) {
  const isActive = data.status === 'working' || data.status === 'thinking'
  const accent = AGENT_COLORS[data.id]
  const dot = statusColor(data.id, data.status)
  const truncated = wasTruncated(data)

  // Real signal: characters streamed so far against this agent's token ceiling.
  const budgetChars = data.maxTokens * CHARS_PER_TOKEN
  const progress = budgetChars > 0 ? Math.min(1, data.output.length / budgetChars) : 0

  return (
    <div
      className={isActive ? 'glass-active agent-active' : 'glass'}
      style={{ width: 180, borderRadius: 16, padding: '14px 16px', position: 'relative' }}
      title={`${AGENT_TOOLTIPS[data.id]} — ${STATUS_LABELS[data.status]}`}
    >
      <Handle
        type="target"
        position={Position.Top}
        style={{ background: accent, border: 'none', width: 8, height: 8 }}
      />
      <Handle
        type="source"
        position={Position.Bottom}
        style={{ background: accent, border: 'none', width: 8, height: 8 }}
      />

      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
        <div
          style={{
            padding: '6px',
            borderRadius: 8,
            color: isActive ? accent : '#94a3b8',
            background: isActive ? `${accent}1a` : 'rgba(148,163,184,0.1)',
            display: 'flex',
          }}
        >
          {ICONS[data.id]}
        </div>
        <div
          style={{
            width: 8,
            height: 8,
            borderRadius: '50%',
            marginLeft: 'auto',
            background: dot,
            boxShadow: isActive ? `0 0 8px ${dot}` : undefined,
          }}
        />
      </div>

      <div style={{ fontSize: 13, fontWeight: 600, color: '#f1f5f9', lineHeight: 1.3 }}>{data.name}</div>
      <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 2 }}>{data.description}</div>

      {data.status === 'complete' && data.tokens > 0 && (
        <div
          title="Content tokens generated by this agent (reasoning tokens excluded)"
          style={{
            marginTop: 8,
            display: 'inline-block',
            padding: '2px 8px',
            borderRadius: 99,
            background: `${accent}1a`,
            color: accent,
            fontSize: 11,
          }}
        >
          {data.tokens.toLocaleString()} content tokens
        </div>
      )}

      {truncated && (
        <div
          title={
            data.finish === 'timeout'
              ? 'This agent ran out of time and its answer was cut short.'
              : 'This agent hit its token ceiling and its answer was cut short.'
          }
          style={{ marginTop: 6, fontSize: 11, color: '#ffa500' }}
        >
          Cut off early
        </div>
      )}

      {data.status === 'stopped' && (
        <div style={{ marginTop: 6, fontSize: 11, color: '#ffa500' }}>Stopped</div>
      )}

      {data.status === 'error' && (
        <div title={data.error} style={{ marginTop: 6, fontSize: 11, color: '#ff3366' }}>
          Failed
        </div>
      )}

      {isActive && (
        <div
          title={`Output length so far: about ${Math.round(progress * 100)}% of this agent's token budget`}
          style={{
            marginTop: 8,
            height: 3,
            background: 'rgba(255,255,255,0.08)',
            borderRadius: 2,
            overflow: 'hidden',
          }}
        >
          <div
            style={{
              height: '100%',
              width: `${Math.max(3, progress * 100)}%`,
              background: accent,
              borderRadius: 2,
              transition: 'width 0.3s ease-out',
            }}
          />
        </div>
      )}
    </div>
  )
}
