import { beforeEach, describe, expect, it, vi } from 'vitest'
import { saveAs } from 'file-saver'
import { buildMarkdown, downloadMarkdown } from '../../src/lib/export'
import { createAgents } from '../../src/lib/agents'

vi.mock('file-saver', () => ({ saveAs: vi.fn() }))

function sampleAgents() {
  const agents = createAgents()
  agents.researcher.output = '- Fact one'
  agents.analyst.output = '   '
  return agents
}

describe('buildMarkdown', () => {
  it('writes the title, credit line and the four sections in pipeline order', () => {
    const markdown = buildMarkdown('How is nuclear power?', sampleAgents())

    expect(markdown.startsWith('# Research Report: How is nuclear power?\n\n*Generated by AgentFlow Multi-Agent AI Pipeline*\n\n---\n\n')).toBe(true)
    expect(markdown).toContain('## Research Findings\n\n- Fact one')
    expect(markdown).toContain('## Analysis\n\nNo output generated.')
    expect(markdown.indexOf('## Research Findings')).toBeLessThan(markdown.indexOf('## Critical Review'))
    expect(markdown.indexOf('## Critical Review')).toBeLessThan(markdown.indexOf('## Final Synthesis'))
  })
})

describe('downloadMarkdown', () => {
  beforeEach(() => {
    vi.mocked(saveAs).mockClear()
  })

  it('saves the same text under a filename built from the query', async () => {
    const agents = sampleAgents()
    downloadMarkdown('How is nuclear power?', agents)

    const call = vi.mocked(saveAs).mock.calls[0]
    expect(call?.[1]).toBe('research-report-how-is-nuclear-power.md')
    const blob = call?.[0]
    expect(blob).toBeInstanceOf(Blob)
    expect(await (blob as Blob).text()).toBe(buildMarkdown('How is nuclear power?', agents))
  })
})
