import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'
import { saveAs } from 'file-saver'
import { jsPDF } from 'jspdf'
import type { AgentRole, AgentState } from '../types'
import { AGENT_LABELS, AGENT_ORDER, slugifyQuery } from './agents'
import { inlineToText, parseBlocks, type Block } from './markdown'

const CREDIT = 'Generated by AgentFlow Multi-Agent AI Pipeline'
const HEADING_LEVELS = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3]

type Agents = Record<AgentRole, AgentState>

function sectionSource(agents: Agents, role: AgentRole): string {
  return agents[role].output.trim() || 'No output generated.'
}

/* ── Markdown ───────────────────────────────────────────────────────────── */

export function buildMarkdown(query: string, agents: Agents): string {
  const lines: string[] = [`# Research Report: ${query}`, '', `*${CREDIT}*`, '', '---', '']
  for (const role of AGENT_ORDER) {
    lines.push(`## ${AGENT_LABELS[role]}`, '', sectionSource(agents, role), '', '')
  }
  return lines.join('\n')
}

export function downloadMarkdown(query: string, agents: Agents): void {
  const blob = new Blob([buildMarkdown(query, agents)], { type: 'text/markdown;charset=utf-8' })
  saveAs(blob, `research-report-${slugifyQuery(query)}.md`)
}

/* ── DOCX ──────────────────────────────────────────────────────────────── */

function docxRuns(text: string, opts: { italics?: boolean; mono?: boolean } = {}): TextRun[] {
  return [
    new TextRun({
      text: inlineToText(text),
      size: 22,
      italics: opts.italics ?? false,
      font: opts.mono ? 'Courier New' : undefined,
    }),
  ]
}

function docxTable(block: Extract<Block, { kind: 'table' }>): Table {
  const toRow = (cells: string[], header: boolean) =>
    new TableRow({
      children: cells.map(
        cell =>
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: inlineToText(cell), size: 20, bold: header })],
              }),
            ],
          }),
      ),
    })

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [toRow(block.header, true), ...block.rows.map(row => toRow(row, false))],
  })
}

function docxBlock(block: Block): Array<Paragraph | Table> {
  switch (block.kind) {
    case 'heading':
      return [
        new Paragraph({
          text: inlineToText(block.text),
          heading: HEADING_LEVELS[block.level - 1] ?? HeadingLevel.HEADING_3,
          spacing: { before: 240, after: 120 },
        }),
      ]
    case 'bullet':
      return [new Paragraph({ children: docxRuns(block.text), bullet: { level: 0 }, spacing: { after: 80 } })]
    case 'numbered':
      return [
        new Paragraph({
          children: docxRuns(`${block.marker}. ${block.text}`),
          indent: { left: 360 },
          spacing: { after: 80 },
        }),
      ]
    case 'quote':
      return [
        new Paragraph({
          children: docxRuns(block.text, { italics: true }),
          indent: { left: 360 },
          spacing: { after: 80 },
        }),
      ]
    case 'code':
      return block.lines.map(
        line => new Paragraph({ children: docxRuns(line, { mono: true }), spacing: { after: 20 } }),
      )
    case 'table':
      return [docxTable(block), new Paragraph({ text: '', spacing: { after: 120 } })]
    case 'rule':
      return [new Paragraph({ text: '', border: { bottom: { style: 'single', size: 6, color: 'CCCCCC' } } })]
    case 'paragraph':
      return [new Paragraph({ children: docxRuns(block.text), spacing: { after: 140 } })]
    case 'blank':
      return []
  }
}

export async function downloadDocx(query: string, agents: Agents): Promise<void> {
  const children: Array<Paragraph | Table> = [
    new Paragraph({
      children: [new TextRun({ text: `Research Report: ${query}`, bold: true, size: 48 })],
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: CREDIT, italics: true, size: 20, color: '888888' })],
      spacing: { after: 600 },
    }),
  ]

  for (const role of AGENT_ORDER) {
    children.push(
      new Paragraph({
        text: AGENT_LABELS[role],
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
    )
    for (const block of parseBlocks(sectionSource(agents, role))) {
      children.push(...docxBlock(block))
    }
  }

  const blob = await Packer.toBlob(new Document({ sections: [{ children }] }))
  saveAs(blob, `research-report-${slugifyQuery(query)}.docx`)
}

/* ── PDF ───────────────────────────────────────────────────────────────── */

interface PdfWriter {
  text: (
    value: string,
    opts: { size?: number; style?: 'normal' | 'bold' | 'italic'; mono?: boolean; color?: [number, number, number]; indent?: number },
  ) => void
  gap: (mm: number) => void
  rule: (color: [number, number, number]) => void
  remaining: () => number
}

function createPdfWriter(pdf: jsPDF): PdfWriter {
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const margin = 20
  let y = margin

  const ensureRoom = (lineHeight: number) => {
    if (y + lineHeight > pageH - margin) {
      pdf.addPage()
      y = margin
    }
  }

  return {
    text(value, opts) {
      const size = opts.size ?? 10
      const indent = opts.indent ?? 0
      const [r, g, b] = opts.color ?? [30, 40, 60]
      pdf.setFontSize(size)
      pdf.setFont(opts.mono ? 'courier' : 'helvetica', opts.style ?? 'normal')
      pdf.setTextColor(r, g, b)
      const lineHeight = size * 0.45
      for (const line of pdf.splitTextToSize(value, pageW - margin * 2 - indent) as string[]) {
        ensureRoom(lineHeight)
        pdf.text(line, margin + indent, y)
        y += lineHeight
      }
    },
    gap(mm) {
      y += mm
    },
    rule([r, g, b]) {
      ensureRoom(2)
      pdf.setDrawColor(r, g, b)
      pdf.setLineWidth(0.2)
      pdf.line(margin, y, pageW - margin, y)
      y += 3
    },
    remaining() {
      return pageH - margin - y
    },
  }
}

const PDF_HEADING_SIZES = [14, 12, 11]

function pdfBlock(w: PdfWriter, block: Block): void {
  switch (block.kind) {
    case 'heading':
      w.gap(2)
      w.text(inlineToText(block.text), {
        size: PDF_HEADING_SIZES[block.level - 1] ?? 11,
        style: 'bold',
        color: [15, 30, 55],
      })
      w.gap(1)
      return
    case 'bullet':
      w.text(`•  ${inlineToText(block.text)}`, { indent: 4 })
      return
    case 'numbered':
      w.text(`${block.marker}.  ${inlineToText(block.text)}`, { indent: 4 })
      return
    case 'quote':
      w.text(inlineToText(block.text), { style: 'italic', indent: 6, color: [90, 100, 120] })
      return
    case 'code':
      w.gap(1)
      for (const line of block.lines) w.text(line || ' ', { size: 9, mono: true, indent: 4, color: [60, 70, 90] })
      w.gap(1)
      return
    case 'table': {
      w.text(block.header.map(inlineToText).join('  |  '), { size: 9, style: 'bold' })
      w.rule([200, 210, 220])
      for (const row of block.rows) w.text(row.map(inlineToText).join('  |  '), { size: 9 })
      w.gap(2)
      return
    }
    case 'rule':
      w.rule([200, 210, 220])
      return
    case 'paragraph':
      w.text(inlineToText(block.text), {})
      return
    case 'blank':
      w.gap(1.5)
      return
  }
}

export function downloadPdf(query: string, agents: Agents): void {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const w = createPdfWriter(pdf)

  w.text('Research Report', { size: 22, style: 'bold', color: [0, 140, 180] })
  w.gap(2)
  w.text(query, { size: 14, color: [30, 40, 60] })
  w.gap(3)
  w.text(CREDIT, { size: 9, color: [120, 130, 150] })
  w.gap(4)
  w.rule([0, 180, 220])
  w.gap(3)

  for (const role of AGENT_ORDER) {
    w.text(AGENT_LABELS[role], { size: 15, style: 'bold', color: [0, 140, 180] })
    w.gap(2)
    for (const block of parseBlocks(sectionSource(agents, role))) pdfBlock(w, block)
    w.gap(3)
    if (w.remaining() > 10) w.rule([200, 210, 220])
    w.gap(3)
  }

  pdf.save(`research-report-${slugifyQuery(query)}.pdf`)
}
